### ISSUE TITLE
Unbearable amount of warnings in newer php versions.

### ISSUE THREAD

**Issue by ShadowSFX** [nachazo/scryfalldler#1]
It's really hard to read through several warnings in newer versions of php because of functions being deprecated. In version 5.6 there is just an issue with the date function. The script functions as it should though, it's just extremely hard to read through the many warnings.

**Comment by nachazo** [comment]
Hi! Well, I made the script with php 7 and didn't notice these ones. Maybe my default config hides that. Anyways, I pushed new version configuring error_reporting for show only error & parse ones, the fastest way (not much time for do more!).
Also maybe you could being experiencing the Windows console ANSI issues, more info here: https://github.com/symfony/symfony/issues/19520
