### ISSUE TITLE
No Licence?

### ISSUE THREAD

**Issue by huwwevans** [nachazo/scryfalldler#5]
Hi, you have not specified a licence for this but it seems to be fairly widely used.  I would also like to use and work on this code.  

Please may I fork your project?

**Comment by nachazo** [comment]
Ey, will add info about license and answer here, closing this issue.
Probably attribution - not commercial, right now I have no time for add it.

**Comment by nachazo** [comment]
Finally done, license GPL v3 added: https://github.com/nachazo/scryfalldler/blob/master/LICENSE
